FROM python:3.12-slim

#https://cloud.google.com/sdk/docs/install?hl=ko#deb
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN apt-get update && apt-get install -y curl git vim net-tools build-essential google-cloud-cli

WORKDIR /home/chatbot

ENV PIP_ROOT_USER_ACTION=ignore
ENV PYTHONPATH=/home/chatbot/src